In [2]:
import numpy as np
np.set_printoptions(linewidth=120)

Multiple-relaxation-time lattice Boltzmann models in three dimensions.pdf

In [3]:
M = np.array([[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [-30,-11,-11,-11,-11,-11,-11,8,8,8,8,8,8,8,8,8,8,8,8],
    [12,-4,-4,-4,-4,-4,-4,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,1,-1,0,0,0,0,1,-1,1,-1,1,-1,1,-1,0,0,0,0],
    [0,-4,4,0,0,0,0,1,-1,1,-1,1,-1,1,-1,0,0,0,0],
    [0,0,0,1,-1,0,0,1,1,-1,-1,0,0,0,0,1,-1,1,-1],
    [0,0,0,-4,4,0,0,1,1,-1,-1,0,0,0,0,1,-1,1,-1],
    [0,0,0,0,0,1,-1,0,0,0,0,1,1,-1,-1,1,1,-1,-1],
    [0,0,0,0,0,-4,4,0,0,0,0,1,1,-1,-1,1,1,-1,-1],
    [0,2,2,-1,-1,-1,-1,1,1,1,1,1,1,1,1,-2,-2,-2,-2],
    [0,-4,-4,2,2,2,2,1,1,1,1,1,1,1,1,-2,-2,-2,-2],
    [0,0,0,1,1,-1,-1,1,1,1,1,-1,-1,-1,-1,0,0,0,0],
    [0,0,0,-2,-2,2,2,1,1,1,1,-1,-1,-1,-1,0,0,0,0],
    [0,0,0,0,0,0,0,1,-1,-1,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-1,-1,1],
    [0,0,0,0,0,0,0,0,0,0,0,1,-1,-1,1,0,0,0,0],
    [0,0,0,0,0,0,0,1,-1,1,-1,-1,1,-1,1,0,0,0,0],
    [0,0,0,0,0,0,0,-1,-1,1,1,0,0,0,0,1,-1,1,-1],
    [0,0,0,0,0,0,0,0,0,0,0,1,1,-1,-1,-1,-1,1,1]
    ])
print(M.shape)
print(M)

(19, 19)
[[  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [-30 -11 -11 -11 -11 -11 -11   8   8   8   8   8   8   8   8   8   8   8   8]
 [ 12  -4  -4  -4  -4  -4  -4   1   1   1   1   1   1   1   1   1   1   1   1]
 [  0   1  -1   0   0   0   0   1  -1   1  -1   1  -1   1  -1   0   0   0   0]
 [  0  -4   4   0   0   0   0   1  -1   1  -1   1  -1   1  -1   0   0   0   0]
 [  0   0   0   1  -1   0   0   1   1  -1  -1   0   0   0   0   1  -1   1  -1]
 [  0   0   0  -4   4   0   0   1   1  -1  -1   0   0   0   0   1  -1   1  -1]
 [  0   0   0   0   0   1  -1   0   0   0   0   1   1  -1  -1   1   1  -1  -1]
 [  0   0   0   0   0  -4   4   0   0   0   0   1   1  -1  -1   1   1  -1  -1]
 [  0   2   2  -1  -1  -1  -1   1   1   1   1   1   1   1   1  -2  -2  -2  -2]
 [  0  -4  -4   2   2   2   2   1   1   1   1   1   1   1   1  -2  -2  -2  -2]
 [  0   0   0   1   1  -1  -1   1   1   1   1  -1  -1  -1  -1   0   0   0   0]
 [  0   0   0  -2  -2   2   2   1   1   1  

In [4]:
e_alpha = np.array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0],
    [0,0,1],
    [0,0,-1],
    [1,1,0],
    [-1,-1,0],
    [1,-1,0 ],
    [-1, 1, 0],
    [1, 0, 1],
    [-1, 0, -1],
    [1, 0, -1],
    [-1, 0, 1],
    [0, 1, 1],
    [0, -1, -1],
    [0, 1, -1],
    [0, -1, 1]
])
print(e_alpha.shape)
print(e_alpha)

(19, 3)
[[ 0  0  0]
 [ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]
 [ 1  1  0]
 [-1 -1  0]
 [ 1 -1  0]
 [-1  1  0]
 [ 1  0  1]
 [-1  0 -1]
 [ 1  0 -1]
 [-1  0  1]
 [ 0  1  1]
 [ 0 -1 -1]
 [ 0  1 -1]
 [ 0 -1  1]]


In [8]:
s1 = 1.19
s2 = 1.4
s4 = 1.2
s16 = 1.98
s10 = s2

s13 = 1

np.diag([0,s1,s2,0,s4,0,s4,0,s4,s9,s10,s9,s10,s13,s13,s16,s16,s16])

NameError: name 's9' is not defined