In [9]:
import numpy as np
from numpy.linalg import norm, inv
np.set_printoptions(linewidth=240)

2D AND 3D VERIFICATION AND VALIDATION OF THE LATTICE BOLTZMANN
METHOD



In [2]:
# kinematic viscosity
nu = 1.516e-5
omega_e = 0
omega_xx = 0
omega_ej = -475/63


In [3]:
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

In [4]:
e_alpha = np.array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0],
    [0,0,1],
    [0,0,-1],
    [1,1,0],
    [-1,-1,0],
    [1,-1,0 ],
    [-1, 1, 0],
    [1, 0, 1],
    [-1, 0, -1],
    [1, 0, -1],
    [-1, 0, 1],
    [0, 1, 1],
    [0, -1, -1],
    [0, 1, -1],
    [0, -1, 1]
])
print(e_alpha.shape)
print(e_alpha)

(19, 3)
[[ 0  0  0]
 [ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]
 [ 1  1  0]
 [-1 -1  0]
 [ 1 -1  0]
 [-1  1  0]
 [ 1  0  1]
 [-1  0 -1]
 [ 1  0 -1]
 [-1  0  1]
 [ 0  1  1]
 [ 0 -1 -1]
 [ 0  1 -1]
 [ 0 -1  1]]


In [5]:
def phi(e):
    p0 = norm(e)**0
    p1 = 19*norm(e)**2 - 30
    p2 = (21*norm(e)**4 - 53*norm(e)**2 + 24)/2
    p3 = e[0]
    p5 = e[1]
    p7 = e[2]
    p4 = (5*norm(e)**2 - 9)*e[0]
    p6 = (5*norm(e)**2 - 9)*e[1]
    p8 = (5*norm(e)**2 - 9)*e[2]
    p9 = 3*e[0]**2 - norm(e)**2
    p11 = e[1]**2 - e[2]**2
    p13 = e[0]*e[1]
    p14 = e[1]*e[2]
    p15 = e[0]*e[2]
    p10 = (3*norm(e)**2 - 5)*(3*e[0]**2 - norm(e)**2)
    p12 = (3*norm(e)**2 - 5)*(e[1]**2 - e[2]**2)
    p16 = (e[1]**2 - e[2]**2)*e[0]
    p17 = (e[2]**2 - e[0]**2)*e[1]
    p18 = (e[0]**2 - e[1]**2)*e[2]
    return np.array([p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18])

In [6]:
M = np.array([phi(e_alpha[i]) for i in range(0, 19)]).transpose()
print(M)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [-30. -11. -11. -11. -11. -11. -11.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.]
 [ 12.  -4.  -4.  -4.  -4.  -4.  -4.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.  -1.   0.   0.   0.   0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [ -0.  -4.   4.  -0.  -0.  -0.  -0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.   1.  -1.   0.   0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [ -0.  -0.  -0.  -4.   4.  -0.  -0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [  0.   0.   0.   0.   0.   1.  -1.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [ -0.  -0.  -0.  -0.  -0.  -4.   4.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [  0.   2.   2.  -1.  -1.  -1.  -1.   1.   1.   1.   1.   1.   1.   1.   1.  -2.  -2.  -2.  -2.]
 [ -0.  -4.  -4.   2

In [7]:
s1 = s4 = s6 = s8 = 0
s2 = 1.19
s3 = s11 = s13 = 1.4
s5 = s7 = s9 = 1.2
s17 = s18 = s19 = 1.98
s10 = s12 = s14 = s15 = s16 = 2/(1 + 6*nu)

S_hat = np.diag([s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19])
print(S_hat)

[[0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        1.19      0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        1.4       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        1.2       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0. 

In [11]:
-inv(M)*S_hat

array([[-0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  5.46783626e-03,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  2.22222222e-02,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00