In [1]:
import numpy as np
from numpy.linalg import norm, inv
np.set_printoptions(linewidth=240)

2D AND 3D VERIFICATION AND VALIDATION OF THE LATTICE BOLTZMANN
METHOD



In [2]:
# kinematic viscosity
nu = 1.516e-5

In [3]:
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

In [4]:
e = np.array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0],
    [0,0,1],
    [0,0,-1],
    [1,1,0],
    [-1,-1,0],
    [1,-1,0 ],
    [-1, 1, 0],
    [1, 0, 1],
    [-1, 0, -1],
    [1, 0, -1],
    [-1, 0, 1],
    [0, 1, 1],
    [0, -1, -1],
    [0, 1, -1],
    [0, -1, 1]
])
print(e.shape)
print(e)

(19, 3)
[[ 0  0  0]
 [ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]
 [ 1  1  0]
 [-1 -1  0]
 [ 1 -1  0]
 [-1  1  0]
 [ 1  0  1]
 [-1  0 -1]
 [ 1  0 -1]
 [-1  0  1]
 [ 0  1  1]
 [ 0 -1 -1]
 [ 0  1 -1]
 [ 0 -1  1]]


In [5]:
def phi(e):
    p0 = norm(e)**0
    p1 = 19*norm(e)**2 - 30
    p2 = (21*norm(e)**4 - 53*norm(e)**2 + 24)/2
    p3 = e[0]
    p5 = e[1]
    p7 = e[2]
    p4 = (5*norm(e)**2 - 9)*e[0]
    p6 = (5*norm(e)**2 - 9)*e[1]
    p8 = (5*norm(e)**2 - 9)*e[2]
    p9 = 3*e[0]**2 - norm(e)**2
    p11 = e[1]**2 - e[2]**2
    p13 = e[0]*e[1]
    p14 = e[1]*e[2]
    p15 = e[0]*e[2]
    p10 = (3*norm(e)**2 - 5)*(3*e[0]**2 - norm(e)**2)
    p12 = (3*norm(e)**2 - 5)*(e[1]**2 - e[2]**2)
    p16 = (e[1]**2 - e[2]**2)*e[0]
    p17 = (e[2]**2 - e[0]**2)*e[1]
    p18 = (e[0]**2 - e[1]**2)*e[2]
    return np.array([p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18])

In [6]:
M = np.array([phi(e[i]) for i in range(0, 19)]).transpose()
print(M.shape)
print(M)

(19, 19)
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [-30. -11. -11. -11. -11. -11. -11.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.]
 [ 12.  -4.  -4.  -4.  -4.  -4.  -4.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.  -1.   0.   0.   0.   0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [ -0.  -4.   4.  -0.  -0.  -0.  -0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.   1.  -1.   0.   0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [ -0.  -0.  -0.  -4.   4.  -0.  -0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [  0.   0.   0.   0.   0.   1.  -1.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [ -0.  -0.  -0.  -0.  -0.  -4.   4.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [  0.   2.   2.  -1.  -1.  -1.  -1.   1.   1.   1.   1.   1.   1.   1.   1.  -2.  -2.  -2.  -2.]
 [ -0.  -4.

In [7]:
f = np.random.uniform(0, 1, size=19)
print(f.shape)
print(f)

(19,)
[0.62355009 0.92222775 0.72845946 0.74898382 0.44399924 0.96517821 0.71913988 0.39461344 0.3130514  0.17445417 0.45203163 0.45780891 0.36181671 0.66713292 0.02236129 0.31259011 0.76526955 0.67568934 0.69367664]


In [8]:
m = M.dot(f)
print(m.shape)
print(m)

(19,)
[ 10.44203457 -26.19040589  -5.33885623   0.7385167   -0.23032474   0.19345733  -1.33146556  -0.73743323  -1.9676249   -1.62710755  -2.89932738  -0.66630421   0.80770086   0.08117903  -0.29150633   0.1301314   -0.93677924  -0.82980624
  -0.11408728]


In [17]:
f_re = inv(M).dot(m)
print(f_re.shape)
print(f_re)

(19,)
[0.62355009 1.92222775 0.72845946 0.74898382 0.44399924 0.96517821 0.71913988 0.39461344 0.3130514  0.17445417 0.45203163 0.45780891 0.36181671 0.66713292 0.02236129 0.31259011 0.76526955 0.67568934 0.69367664]
True


In [19]:
rho = m[0] # density
en = m[1] # energy
epsilon = m[2] # energy square
jx = m[3] # momentum x direction
qx = m[4] # energy flux x direction
jy = m[5] # momentum y direction
qy = m[6] # energy flux y direction
jz = m[7] # momentum z direction
qz = m[8] # energy flux z direction
pxx = m[9]/3 # symmetric stress tensor
pixx = m[10]/3
pww = m[11]
piww = m[12]
pxy = m[13]
pyz = m[14]
pxz = m[15]
mx = m[16]
my = m[17]
mz = m[18]

omega_e = 0
omega_xx = 0
omega_ej = -475/63

10.442034569917402

In [10]:
s1 = s4 = s6 = s8 = 0
s2 = 1.19
s3 = s11 = s13 = 1.4
s5 = s7 = s9 = 1.2
s17 = s18 = s19 = 1.98
s10 = s12 = s14 = s15 = s16 = 2/(1 + 6*nu)

S_hat = np.diag([s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19])
print(S_hat.shape)
print(S_hat)

(19, 19)
[[0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        1.19      0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        1.4       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        1.2       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.  