2D AND 3D VERIFICATION AND VALIDATION OF THE LATTICE BOLTZMANN METHOD

https://publications.polymtl.ca/1927/1/2015_MatteoPortinari.pdf

Lattice Boltzmann Method Simulation of 3-D Natural Convection with Double MRT Model

https://arxiv.org/pdf/1511.04633.pdf

Multiple-relaxation-time Lattice Boltzmann Models in 3D

https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20020075050.pdf

In [1]:
import numpy
numpy.set_printoptions(linewidth=200)

from numpy import array, diag
from numpy.linalg import norm, inv

In [2]:
# kinematic viscosity
nu = 1.516e-5

In [3]:
e = array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0],
    [0,0,1],
    [0,0,-1],
    [1,1,0],
    [-1,-1,0],
    [1,-1,0 ],
    [-1, 1, 0],
    [1, 0, 1],
    [-1, 0, -1],
    [1, 0, -1],
    [-1, 0, 1],
    [0, 1, 1],
    [0, -1, -1],
    [0, 1, -1],
    [0, -1, 1]
])
print(e.shape)
print(e)

(19, 3)
[[ 0  0  0]
 [ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]
 [ 1  1  0]
 [-1 -1  0]
 [ 1 -1  0]
 [-1  1  0]
 [ 1  0  1]
 [-1  0 -1]
 [ 1  0 -1]
 [-1  0  1]
 [ 0  1  1]
 [ 0 -1 -1]
 [ 0  1 -1]
 [ 0 -1  1]]


In [4]:
def phi(e):
    p0 = norm(e)**0
    p1 = 19*norm(e)**2 - 30
    p2 = (21*norm(e)**4 - 53*norm(e)**2 + 24)/2
    p3 = e[0]
    p5 = e[1]
    p7 = e[2]
    p4 = (5*norm(e)**2 - 9)*e[0]
    p6 = (5*norm(e)**2 - 9)*e[1]
    p8 = (5*norm(e)**2 - 9)*e[2]
    p9 = 3*e[0]**2 - norm(e)**2
    p11 = e[1]**2 - e[2]**2
    p13 = e[0]*e[1]
    p14 = e[1]*e[2]
    p15 = e[0]*e[2]
    p10 = (3*norm(e)**2 - 5)*(3*e[0]**2 - norm(e)**2)
    p12 = (3*norm(e)**2 - 5)*(e[1]**2 - e[2]**2)
    p16 = (e[1]**2 - e[2]**2)*e[0]
    p17 = (e[2]**2 - e[0]**2)*e[1]
    p18 = (e[0]**2 - e[1]**2)*e[2]
    return array([p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18])

In [5]:
M = array([phi(e[i]) for i in range(0, 19)]).transpose()
print(M.shape)
print(M)

(19, 19)
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [-30. -11. -11. -11. -11. -11. -11.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.]
 [ 12.  -4.  -4.  -4.  -4.  -4.  -4.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.  -1.   0.   0.   0.   0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [ -0.  -4.   4.  -0.  -0.  -0.  -0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.   1.  -1.   0.   0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [ -0.  -0.  -0.  -4.   4.  -0.  -0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [  0.   0.   0.   0.   0.   1.  -1.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [ -0.  -0.  -0.  -0.  -0.  -4.   4.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [  0.   2.   2.  -1.  -1.  -1.  -1.   1.   1.   1.   1.   1.   1.   1.   1.  -2.  -2.  -2.  -2.]
 [ -0.  -4.

In [6]:
s1 = s4 = s6 = s8 = 0
s2 = 1.19
s3 = s11 = s13 = 1.4
s5 = s7 = s9 = 1.2
s17 = s18 = s19 = 1.98
s10 = s12 = s14 = s15 = s16 = 2/(1 + 6*nu)

S_hat = diag([s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19])
print(S_hat.shape)
print(S_hat)

(19, 19)
[[0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        1.19      0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        1.4       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        1.2       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.  

In [7]:
def eq(m):
    rho = m[0] # density
    en = m[1] # energy
    epsilon = m[2] # energy square
    jx = m[3] # momentum
    qx = m[4] # energy flux
    jy = m[5]
    qy = m[6]
    jz = m[7]
    qz = m[8]
    pxx = m[9]/3 # symmetric viscous stress tensor
    pixx = m[10]/3
    pww = m[11]
    piww = m[12]
    pxy = m[13]
    pyz = m[14]
    pxz = m[15]
    mx = m[16] # antisymmetric third-order moment
    my = m[17]
    mz = m[18]

    omega_e = 0 # model stability constants
    omega_xx = 0
    omega_ej = -475/63
    rho_0 = 1 #  mean density in system

    rho_eq = rho
    en_eq = -11*rho + 19/rho_0*(jx*jx + jy*jy + jz*jz)
    epsilon_eq = omega_e*rho + omega_ej/rho_0*(jx*jx + jy*jy + jz*jz)
    jx_eq = jx
    qx_eq = -2/3*jx
    jy_eq = jy
    qy_eq = -2/3*jy
    jz_eq = jz
    qz_eq = -2/3*jz
    pxx_eq = 1/rho_0*(2*jx*jx - (jy*jy + jz*jz))
    pixx_eq = omega_xx*1/rho_0*(2*jx*jx - (jy*jy + jz*jz))
    pww_eq = 1/rho_0*(jy*jy - jz*jz)
    piww_eq = omega_xx/rho_0*(jy*jy - jz*jz)
    pxy_eq = jx*jy/rho_0
    pyz_eq = jy*jz/rho_0
    pxz_eq = jx*jz/rho_0
    mx_eq = 0
    my_eq = 0
    mz_eq = 0
    return array([rho_eq, en_eq, epsilon_eq, jx_eq, qx_eq, jy_eq, qy_eq, jz_eq, qz_eq, pxx_eq, pixx_eq, pww_eq, piww_eq, pxy_eq, pyz_eq, pxz_eq, mx_eq, my_eq, mz_eq])

In [8]:
f = array([0.91011621, 0.54496171, 0.05846047, 0.79559384, 0.42421372, 0.9898699, 0.50646559, 0.06636255, 0.94901775, 0.14879123, 0.50507259, 0.0282714, 0.12636962, 0.10803223, 0.93517096, 0.65583689, 0.68560732, 0.61537474, 0.74262386])
print(f.shape)
print(f)

(19,)
[0.91011621 0.54496171 0.05846047 0.79559384 0.42421372 0.9898699  0.50646559 0.06636255 0.94901775 0.14879123 0.50507259 0.0282714  0.12636962 0.10803223 0.93517096 0.65583689 0.68560732 0.61537474
 0.74262386]


In [9]:
m = M.dot(f)
print(m.shape)
print(m)

(19,)
[ 9.79621258e+00 -1.92864547e+01  3.20966474e+00 -1.67767227e+00 -4.11017847e+00 -3.12013270e-01 -2.16891387e+00  1.30992351e+00 -1.10709804e+00 -4.04109598e+00  4.86800090e-01  1.94871980e-01
  1.02445577e+00  3.61516480e-01 -1.65543900e-02 -8.88562170e-01 -3.13699610e-01  3.69354290e-01  6.31561820e-01]


In [10]:
m_eq = eq(m)
print(m_eq.shape)
print(m_eq)

(19,)
[  9.79621258 -19.82945194 -34.89241525  -1.67767227   1.11844818  -0.31201327   0.20800885   1.30992351  -0.87328234   3.81591661   0.          -1.61854732  -0.           0.52345601  -0.40871352
  -2.19762235   0.           0.           0.        ]


In [11]:
m_diff = m - m_eq
m_relax = S_hat.dot(m_diff)
f_diff = -inv(M).dot(m_relax)
print(f_diff.shape)
print(f_diff)

(19,)
[-2.53204134  1.13303094  2.38790133 -0.07363015  0.4968313   0.54892113  0.6050369   0.32937367 -0.46507097 -0.15799687 -0.30155003 -0.14942258 -0.00926471  1.4581127   1.00108225 -1.12067161
 -1.40710864 -1.05520019 -0.68833314]
