In [1]:
import numpy as np
from numpy.linalg import norm, inv
np.set_printoptions(linewidth=240)

2D AND 3D VERIFICATION AND VALIDATION OF THE LATTICE BOLTZMANN
METHOD



In [2]:
# kinematic viscosity
nu = 1.516e-5

In [3]:
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    # Get the number of vectors.
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

In [4]:
e = np.array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0],
    [0,0,1],
    [0,0,-1],
    [1,1,0],
    [-1,-1,0],
    [1,-1,0 ],
    [-1, 1, 0],
    [1, 0, 1],
    [-1, 0, -1],
    [1, 0, -1],
    [-1, 0, 1],
    [0, 1, 1],
    [0, -1, -1],
    [0, 1, -1],
    [0, -1, 1]
])
print(e.shape)
print(e)

(19, 3)
[[ 0  0  0]
 [ 1  0  0]
 [-1  0  0]
 [ 0  1  0]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]
 [ 1  1  0]
 [-1 -1  0]
 [ 1 -1  0]
 [-1  1  0]
 [ 1  0  1]
 [-1  0 -1]
 [ 1  0 -1]
 [-1  0  1]
 [ 0  1  1]
 [ 0 -1 -1]
 [ 0  1 -1]
 [ 0 -1  1]]


In [5]:
def phi(e):
    p0 = norm(e)**0
    p1 = 19*norm(e)**2 - 30
    p2 = (21*norm(e)**4 - 53*norm(e)**2 + 24)/2
    p3 = e[0]
    p5 = e[1]
    p7 = e[2]
    p4 = (5*norm(e)**2 - 9)*e[0]
    p6 = (5*norm(e)**2 - 9)*e[1]
    p8 = (5*norm(e)**2 - 9)*e[2]
    p9 = 3*e[0]**2 - norm(e)**2
    p11 = e[1]**2 - e[2]**2
    p13 = e[0]*e[1]
    p14 = e[1]*e[2]
    p15 = e[0]*e[2]
    p10 = (3*norm(e)**2 - 5)*(3*e[0]**2 - norm(e)**2)
    p12 = (3*norm(e)**2 - 5)*(e[1]**2 - e[2]**2)
    p16 = (e[1]**2 - e[2]**2)*e[0]
    p17 = (e[2]**2 - e[0]**2)*e[1]
    p18 = (e[0]**2 - e[1]**2)*e[2]
    return np.array([p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18])

In [6]:
M = np.array([phi(e[i]) for i in range(0, 19)]).transpose()
print(M.shape)
print(M)

(19, 19)
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [-30. -11. -11. -11. -11. -11. -11.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.   8.]
 [ 12.  -4.  -4.  -4.  -4.  -4.  -4.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.  -1.   0.   0.   0.   0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [ -0.  -4.   4.  -0.  -0.  -0.  -0.   1.  -1.   1.  -1.   1.  -1.   1.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.   1.  -1.   0.   0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [ -0.  -0.  -0.  -4.   4.  -0.  -0.   1.  -1.  -1.   1.   0.   0.   0.   0.   1.  -1.   1.  -1.]
 [  0.   0.   0.   0.   0.   1.  -1.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [ -0.  -0.  -0.  -0.  -0.  -4.   4.   0.   0.   0.   0.   1.  -1.  -1.   1.   1.  -1.  -1.   1.]
 [  0.   2.   2.  -1.  -1.  -1.  -1.   1.   1.   1.   1.   1.   1.   1.   1.  -2.  -2.  -2.  -2.]
 [ -0.  -4.

In [7]:
f = np.random.uniform(0, 1, size=19)
print(f.shape)
print(f)

(19,)
[0.52110254 0.12999099 0.96644694 0.22687124 0.33465859 0.32763748 0.27609938 0.80647484 0.02732287 0.27682607 0.89150123 0.9931904  0.50165265 0.9411163  0.44211995 0.23637773 0.92894029 0.65925407 0.87541869]


In [8]:
m = M.dot(f)
print(m.shape)
print(m)

(19,)
[10.36300224 20.12973346  4.78660708  0.31855497  4.50083472  0.3773126   0.91624933 -0.43231843 -0.69000895  0.50783189 -2.57499557 -0.91816132 -0.79154022 -0.33452959 -0.36935474  0.1116068  -0.82605729 -2.30255431  0.46893933]


In [9]:
rho = m[0] # density
en = m[1] # energy
epsilon = m[2] # energy square
jx = m[3] # momentum
qx = m[4] # energy flux
jy = m[5]
qy = m[6]
jz = m[7]
qz = m[8]
pxx = m[9]/3 # symmetric viscous stress tensor
pixx = m[10]/3
pww = m[11]
piww = m[12]
pxy = m[13]
pyz = m[14]
pxz = m[15]
mx = m[16] # antisymmetric third-order moment
my = m[17]
mz = m[18]

In [13]:
omega_e = 0 # model stability constants
omega_xx = 0
omega_ej = -475/63
rho_0 = 1 #  mean density in system

rho_eq = rho
en_eq = -11*rho + 19/rho_0*(jx*jx + jy*jy + jz*jz)
epsilon_eq = omega_e*rho + omega_ej/rho_0*(jx*jx + jy*jy + jz*jz)
jx_eq = jx
qx_eq = -2/3*jx
jy_eq = jy
qy_eq = -2/3*jy
jz_eq = jz
qz_eq = -2/3*jz
pxx_eq = 1/rho_0*(2*jx*jx - (jy*jy + jz*jz))
pixx_eq = omega_xx*1/rho_0*(2*jx*jx - (jy*jy + jz*jz))
pww_eq = 1/rho_0*(jy*jy - jz*jz)
piww_eq = omega_xx/rho_0*(jy*jy - jz*jz)
pxy_eq = jx*jy/rho_0
pyz_eq = jy*jz/rho_0
pxz_eq = jx*jz/rho_0
mx_eq = 0
my_eq = 0
mz_eq = 0

m_eq = np.array([rho_eq, en_eq, epsilon_eq, jx_eq, qx_eq, jy_eq, qy_eq, jz_eq, qz_eq, pxx_eq, pixx_eq, pww_eq, piww_eq, pxy_eq, pyz_eq, pxz_eq, mx_eq, my_eq, mz_eq])
print(m_eq.shape)
print(m_eq)

(19,)
[ 1.03630022e+01 -1.05808940e+02 -3.24765263e+00  3.18554966e-01 -2.12369977e-01  3.77312605e-01 -2.51541737e-01 -4.32318435e-01  2.88212290e-01 -1.26309498e-01 -0.00000000e+00 -4.45344270e-02 -0.00000000e+00  1.20194804e-01
 -1.63119195e-01 -1.37717184e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00]


In [11]:
s1 = s4 = s6 = s8 = 0
s2 = 1.19
s3 = s11 = s13 = 1.4
s5 = s7 = s9 = 1.2
s17 = s18 = s19 = 1.98
s10 = s12 = s14 = s15 = s16 = 2/(1 + 6*nu)

S_hat = np.diag([s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19])
print(S_hat.shape)
print(S_hat)

(19, 19)
[[0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        1.19      0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        1.4       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        1.2       0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.        0.       ]
 [0.        0.        0.  